@echo off
@rem echo Setting up virtual environment ...
@rem python -m venv venv
@rem echo Installing requirements ...
@rem .\venv\Scripts\pip install -r requirements.txt cx_Freeze
@rem echo Building binaries ...
@rem .\venv\Scripts\cxfreeze -c run_seekers.py --target-dir dist/seekers --include-files config.ini
@rem .\venv\Scripts\cxfreeze -c run_client.py --target-dir dist/client
echo Compress artifacts ...
for /d %%a in (dist\*) do (powershell Compress-Archive ".\%%a\*" "%%~na.zip")
echo Finished!